// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5cLMrI4dQb1VPNnG9ELI8Q4u2Nnv2R8A',
    appId: '1:866685804903:web:653d5bc49622c22a2e4fc2',
    messagingSenderId: '866685804903',
    projectId: 'ozze-97320',
    authDomain: 'ozze-97320.firebaseapp.com',
    storageBucket: 'ozze-97320.appspot.com',
    measurementId: 'G-XNJ3ZVFPY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgfz49WjTkSEH3TCKKwANWH9rd6L29Vu0',
    appId: '1:866685804903:android:7dd4a7f43a990d4e2e4fc2',
    messagingSenderId: '866685804903',
    projectId: 'ozze-97320',
    storageBucket: 'ozze-97320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsNRTudohqMP_Rb5pOKDIS9_tcTLNOjng',
    appId: '1:866685804903:ios:5463a210f32ae8502e4fc2',
    messagingSenderId: '866685804903',
    projectId: 'ozze-97320',
    storageBucket: 'ozze-97320.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
